CARRITO/urls.py
from django.urls.conf import include
from CARRITO import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static



# app_name = "CARRITO"
urlpatterns = [
    path('', views.inicio, name='Home'),
    path('buscar/', views.buscar, name='Buscar'),
    path('producto/', views.producto, name='Producto'),
    path('producto/<int:id>', views.productoEditar, name='EditarProducto'),
    path('eliminarProducto/<int:id>', views.productoEliminar, name='EliminarProducto'),
    path('producto/<int:id>/', views.verProducto, name='verProducto'), 
    path('agregarProducto/', views.agregarProducto, name='Agregar'), 
    path('contacto/', views.contacto, name='Contacto'),
    path('acerca_de/', views.acerca_de, name='Aacerca de'),
    path('carrito/', views.carrito, name='Carrito'),
    path('carrito/<int:id>', views.agregarCarrito, name='AgregarCarrito'),
    path('vaciarCarrito/', views.vaciarCarrito, name='vaciarCarrito'),
    path('eliminarCarrito/<int:id>', views.eliminarDelCarrito, name='EliminarDelCarrito'),
    path('USUARIO/', include('USUARIOS.urls')), 
    path('agregarCategoria/', views.agregarCategoria, name='AgregarCategoria'), 
    path('categoria/<int:id>', views.productoCategoria, name='Categoria'),
    
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TIENDA/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('CARRITO.urls')),
    path('USUARIO/',include('USUARIOS.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

CARRITO/models.py
from django.db import models
from django.contrib.auth.models import User



# Create your models here.


class Categoria(models.Model):
    descripcion = models.TextField(max_length=100)
    def __str__(self):
        return f"{self.descripcion}"
        
    
    
class Producto(models.Model):
    titulo =  models.CharField(max_length=200)
    imagenProducto =  models.ImageField(upload_to='productos',blank = True, null = True)
    descripcion = models.CharField(max_length=254)
    precio =  models.FloatField()
    categoria = models.ForeignKey(Categoria,on_delete= models.CASCADE, null=False)
    created =  models.DateTimeField(auto_now_add=True)
    updated =  models.DateTimeField(auto_now_add=True)
        
    def __unicode__(self,):
            return str(self.imagenProducto)   
    def __str__(self):
        return f'{self.titulo} | {self.descripcion} | Categoria {self.categoria}'
    

    
class Carrito(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, related_name='usuario')
    productos = models.ForeignKey(Producto, on_delete=models.CASCADE,related_name="carrito")
    cantidad =  models.IntegerField()
    
    
    def __srt__(self):
        return f'{self.usuario} | {self.productos} | {self.cantidad}' 
        
    
    class Meta:
        verbose_name='Carrito'
    

CARRITO/forms.py
from django import forms
from django.forms import fields
from .models import Carrito, Producto, Categoria

class formulario_contacto(forms.Form):
    asunto=  forms.CharField()
    email = forms.EmailField()
    mensaje =  forms.CharField()
class ProductoForm(forms.ModelForm):
    categoria_id =forms.ModelChoiceField(queryset=Categoria.objects.all())
    class Meta:
        
        model = Producto
        fields = ['titulo', 'imagenProducto', 'descripcion','precio',]
   
class CarritoForm(forms.ModelForm):
    class Meta:
        model = Carrito
        fields = ['usuario', 'productos' , 'cantidad']

        

CARRITO/views.py
from django.shortcuts import render
from CARRITO.models import Producto
from django.shortcuts import render
from django.core.mail import send_mail
from .models import *
from .models import Categoria
from .forms import formulario_contacto, ProductoForm, CarritoForm
from django.db.models import Q



from django.contrib.auth.decorators import login_required

# Create your views here.
def inicio(request):
    ultimos = Producto.objects.all().order_by('-id')[:3]
    for pr in ultimos:
        pr.titulo =  pr.titulo[:43]
        pr.descripcion =  pr.descripcion[:70]
    otros = Producto.objects.all().order_by('-id')[3:10]
    return render(request,'home.html',{"ultimos":ultimos,"otros":otros})

def verProducto(request,id):
    producto = Producto.objects.get(pk = id) 
    if producto:
        return render(request,'productos/verProducto.html',{'producto': producto})
    else:
        return render(request,'productos/verProducto.html',{'vacio': 'No existe'})
        
def buscar(request):
    producto = request.GET['inputProducto']
    if request.GET:
        if len(producto)>20:
            mensaje = "Texto de busqueda demasiado largo, intente otra vez"
            return render(request,"",{"mensaje":mensaje,'query':producto})
        else:
            productos_encontrados_d = Producto.objects.filter(descripcion__icontains = producto)
            productos_encontrados_t = Producto.objects.filter(titulo__icontains = producto)
            
            productos_encontrados = productos_encontrados_d.union(productos_encontrados_t)
            return render(request,"productos/resultados_buqueda.html",{"productos_encontrados":productos_encontrados,"query":producto})
    else:
        return render(request,"productos/resultados_buqueda.html",{"mensaje":'No se encontraron Productos','query':producto})



def contacto(request):
    if request.method=="POST":
        mi_formulario = formulario_contacto(request.POST)
        if mi_formulario.is_valid():
            informacion_formulario =  mi_formulario.cleaned_data
            send_mail(informacion_formulario['asunto'],informacion_formulario['mensaje'],informacion_formulario.get('email',''),['miemail@gmail.com'],)
            return render(request,"contacto/gracias.html")
    mi_formulario =  formulario_contacto()
    return render(request,"contacto/contacto.html",{"formulario":mi_formulario})


def acerca_de(request):
    return render(request,"acerca_de.html")

def producto(request):
    productos = Producto.objects.all()
    for producto in productos:
        producto.titulo =  producto.titulo[:43]
        producto.descripcion =  producto.descripcion[:60]
    return render(request,"productos/producto.html",{'productos':productos})



@login_required(login_url='login')
def productoEditar(request, id):
    
    if request.method=="POST": 

        prod = Producto.objects.get(pk=id)
        
        categoria = int(request.POST['categoria_id'])
        
        titulo = request.POST['titulo']
        if titulo:
            prod.titulo = titulo   
            
        descripcion  = request.POST['descripcion']
        if descripcion:
            prod.descripcion = descripcion
        
        precio = request.POST['precio']
        if precio:
            prod.precio = (precio)
        
        if request.FILES.get('imagenProducto'):
            prod.imagenProducto.delete()
            prod.imagenProducto = request.FILES.get('imagenProducto')
        
        if categoria:  
            prod.categoria_id = categoria
        
        prod.save()
        return render(request,'productos/verProducto.html',{'producto': prod})
              
    producto = Producto.objects.get(pk = id)
    categorias = Categoria.objects.all()
    form = ProductoForm(request.POST)
    return render (request,'productos/editar.html',{'form':form, 'producto':producto, 'categorias':categorias})

def productoEliminar(request, id):
    Producto.objects.filter(pk=id).delete()
    mensaje = "Producto eliminado."
    productos =  Producto.objects.all()
    for producto in productos:
        producto.titulo =  producto.titulo[:43]
        producto.descripcion =  producto.descripcion[:60]
    return render (request, 'productos/producto.html',{'productos':productos, 'mensaje':mensaje})
   
    





@login_required(login_url='login')
def carrito(request):
    
    user = request.user
    id_user =  user.id
    productos =  Carrito.objects.filter(usuario_id = id_user).select_related('productos')
    
    total = 0
    for p in productos:
        producto = Producto.objects.get(pk = p.productos_id)
        total = total + (producto.precio* p.cantidad)        
    if request.user.is_authenticated:
        return render(request,"carrito/carrito.html",{'carrito': productos, 'vacio':'No tiene productos en su carrito', 'total':total})
    else:
        return render(request,"carrito/carrito.html", {'vacio': 'No tiene productos en su carrito'})   
    
@login_required(login_url='login')   
def agregarCarrito(request ,id):
    user = request.user
    producto =  Producto.objects.get(pk = id)
    existente = Carrito.objects.filter(Q(usuario_id=user.id) & Q(productos_id=id)).exists()
    
    if existente:
        art = Carrito.objects.get(Q(usuario_id=user) & Q(productos_id=producto))
        cant = art.cantidad + 1 
        Carrito.objects.filter(Q(usuario_id=user.id) & Q(productos_id=id)).update(cantidad = cant)
        return render(request,'productos/verProducto.html',{'producto': producto,'mensaje':'Modifico la cantidad en un producto de su carrito'})
    else:
        cantidad = 1
        form =  CarritoForm({'usuario':user , 'producto':producto, 'cantidada':cantidad})
        if form.is_valid:
            obj = Carrito()
            obj.usuario = user
            obj.productos = producto
            obj.cantidad = cantidad
            obj.save()
            return render(request,'productos/verProducto.html',{'producto': producto, 'mensaje' : 'Producto agregado al carrito'})

def eliminarDelCarrito(request,id):
    user = request.user

    Carrito.objects.filter(Q(usuario_id=user.id) & Q(productos_id = id)).delete()
    
    productos =  Carrito.objects.filter(usuario_id = user.id)
    return render(request,"carrito/carrito.html", {'carrito': productos,'mensaje': 'No tiene productos en su carrito','vacio':'Su carrito esta vacio'}) 
   
    
    
 
@login_required(login_url='login')   
def agregarProducto(request):  
    if  request.method == "POST":
        form = ProductoForm(request.POST or None)
        categoria = int(request.POST["categoria_id"])
        # imagen = str(request.POST["imagenProducto"])
        if form.is_valid():
            obj =  Producto()
            obj.titulo = form.cleaned_data['titulo']
            obj.descripcion = form.cleaned_data['descripcion']
            obj.imagenProducto = request.FILES.get('imagenProducto')
            obj.precio = form.cleaned_data['precio']
            obj.categoria_id = categoria
            obj.save()
            mensaje = f'Producto: {obj.titulo} agregado.' 
            form = ProductoForm()
            return render(request,'productos/agregarProducto.html',{'form':form, 'mensaje':mensaje})
            
        else:
            return render(request,'productos/agregarProducto.html',{'error':'Error'})

             
    form = ProductoForm()
    categorias =  Categoria.objects.all()
    return render(request,'productos/agregarProducto.html',{'form':form,'categorias':categorias})

def agregarCategoria(request):
    
    if request.method == "POST":
        descripcion = request.POST["descripcion"]
        obj =  Categoria()
        obj.descripcion = descripcion
        obj.save()
        form = ProductoForm()
        return render(request,'productos/agregarProducto.html',{'form': form})   
    else:
        return render(request,'productos/agregarCategoria.html')
    
def productoCategoria(request, id):
    categoria =  Categoria.objects.get(pk = id)
    if  request.method == "GET": 
        productos = Producto.objects.filter(categoria_id = id)
        if productos:
            return render(request,'productos/resultados_buqueda.html',{'productos': productos,'categoria':categoria.descripcion})
        else:
            return render(request,'productos/resultados_buqueda.html',{'mensaje': 'No hay productos con esta categoria','categoria':categoria.descripcion})
        
        
        
def vaciarCarrito(request):
    user = request.user
    id_user = user.id
    Carrito.objects.filter(usuario_id = id_user).delete()
    
    productos =  Carrito.objects.filter(usuario_id = user.id)
    return render(request,"carrito/carrito.html", {'carrito': productos,'mensaje': 'No tiene productos en su carrito','vacio':'Su carrito esta vacio'}) 

CARRITO/templates/productos/agregarCategoria.html
{% extends "layout.html" %}

{% block title %} 
    Agregar Categoria 
{%endblock%}

       
{% block content %} 
     <form action="{% url 'AgregarCategoria' %}" method="POST">
        {% csrf_token %}

   
        <div class="formulario">
            <div class="contenedor_form">
               <div class="campos_forms">
                    <label class="eqtiqueta_form">Descripcion</label>
                    <input class="input_campo" type="text" name="descripcion" placeholder="Descripcion Categoria ">
                </div>
                <div class="campos_forms" style="margin-top: 1em;">
                    <input class= "boton_ver_mas" type="submit" value="Agregar">
                </div>
            </div>
        </div>

             
             
    </form>
{%endblock%}

CARRITO/templates/productos/agregarProducto.html
{% extends "layout.html" %}

{% block title %} 
    Agregar Producto
{%endblock%}


{% block content %} 

{% load static %}

<form action="{% url 'Agregar' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <p id='mensaje' hidden=true>{{mensaje}}</p>
        {{error}}
        
        
        {% if mensaje %}
            <script>
                mensaje = document.querySelector('#mensaje')
                mensaje.hidden = false
                setTimeout(function(){ 
                    mensaje.hidden = true
                }, 7000);
            </script>
        {% endif %}

        <div class="formulario">
        <div class="contenedor_form">


        <div class="campos_forms">
            <label class="eqtiqueta_form" for="{{from.titulo}}">Titulo</label>
            <textarea name="titulo" id="id_titulo" cols="40" rows="5" placeholder="Titulo" ></textarea>
         </div>
        
        <div class="campos_forms">
            <label class="eqtiqueta_form" for="{{from.descripcion}}">Descripcion</label>
            <textarea name="descripcion" id="id_descripcion" cols="40" rows="5" placeholder="Descripcion" ></textarea>  
        </div>

        <div class="campos_forms">
            <label class="eqtiqueta_form" for="{{from.precio}}">Precio</label>
            <input class="input_campo" type="number" name="precio" step="any" required="" id="id_precio" placeholder="$ Precio">
        </div>
        
        <div class="campos_forms">
            <label class="eqtiqueta_form" for="{{from.imagenProducto}}">Imagen</label>
            <input class="input_campo" type="file" name="imagenProducto" accept="image/*" id="id_imagenProducto" placeholder="Imagen Producto"> 
        </div>
        
        <div class="campos_forms" style="border: #ccc dotted; margin-top: 2em;">
            
            <select class="input_campo" name="categoria_id" required="" id="id_categoria_id">
                <option value="Cabecera">Categorias</option>
                {% for categoria in categorias%}
                        <option value="{{categoria.id}}">{{categoria.descripcion}}</option>
                {% endfor %}
              </select>  
        </div>
        <div  class="campos_forms">
            <a class="link_agregar" href="{% url 'AgregarCategoria' %}">Agregar Categoria</a>
        </div>

        <div  class="campos_forms" style="margin-top: 2em;">
            <input class="boton_ver_mas" type="submit" value="Agregar" >
        </div>
                

        </div>
        </div>
</form>



       

{%endblock%}

CARRITO/templates/productos/editar.html
{% extends "layout.html" %}

{% block title %} 
    Editar Producto
{%endblock%}


{% block content %} 



        <form action="{% url 'EditarProducto' producto.id %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="formulario">
            <div class="contenedor_form">

            <div class="campos_forms">
                <p class="etiqueta_form">Titulo</p>
                <textarea class="input_campo" name="titulo" id="titulo" cols="40" rows="5">{{producto.titulo}}</textarea>
            </div>
            

            <div class="campos_forms">
                <p class="etiqueta_form">Descripcion</p>
                <textarea class="input_campo" name="descripcion" id="descripcion" cols="40" rows="5">{{producto.descripcion}}</textarea>
            </div>


            <div class="campos_forms">
                    <p class="etiqueta_form">Imagen actual</p>
                    <img id="imagen_actual" src="{{ producto.imagenProducto.url }}" alt="Imagen Produco" width="20%" height="35%">
                    <p style="margin-top: 2em;" class="eqtiqueta_form">Nueva imagen</p>
                    <input class="input_campo" type="file" name="imagenProducto" accept="image/*" id="imagenProducto"> 
            </div>



            <div class="campos_forms" style="margin-top: 2em;">
                <p class="etiqueta_form">Precio: actual ${{producto.precio}}</p>
                <input type="number" class="input_campo" name="precio" id="precio" value="{{producto.precio}}" placeholder="$ Nuevo Precio">
            </div>


            <div class="campos_forms" style="margin-top: 2em;">
                <p class="etiqueta_form">Categoria</p>

            <select class="input_campo" name="categoria_id" required="" id="id_categoria_id" style="border: #ccc dotted;">
                    {% for categoria in categorias%}
                        {% if categoria.id == producto.categoria_id  %}
                            <option value="{{categoria.id}}" selected>{{categoria.descripcion}}</option>
                        {% else %}
                            <option value="{{categoria.id}}">{{categoria.descripcion}}</option>
                        {% endif %}
                    {% endfor %}
                  </select> 
            </div>

            
            
            <div class="row" style="margin-top: 2em;">

            <div class="campos_forms col-6">
                <input class="boton_enviar" type="submit" value="Editar">
            </div>

            <div class="campos_forms col">
                <a class="boton_enviar" href="{% url 'verProducto' producto.id %}">Cancelar</a>
            </div> 
            </div>
            


        </div>
        </div>

        </form>



       
{%endblock%}

CARRITO/templates/productos/producto.html
{% extends "layout.html" %}

{% block title %} 
    Producto
{%endblock%}


{% block content %} 

<div class="container">
            {% load static %}
            {% if mensaje%}
                <div id="mensaje">{{mensaje}}</div>
                <script>
                    mensaje = document.querySelector('#mensaje')
                    mensaje.hidden = false
                    setTimeout(function(){ 
                        mensaje.hidden = true
                    }, 7000);
                </script>
            {% endif %}
           

            <div class="row">
                <div class="card-group">
                        {% for pr in productos %}
                        <div class="col-lg-4 col-sm-6 col-md-6 col-xs-12 d-flex align-items-stretch"> 
                            <div class="card">
                                <a href="{% url 'verProducto' pr.id %}"><img src="{{ pr.imagenProducto.url }}" class="card-img-top" alt="Imagen producto" height="200px" width="auto" ></a>
                                <div class="card-body">
                                    <h5 class="card-title"><a class='link_pr_carro' href="{% url 'verProducto' pr.id %}">{{pr.titulo}}</a></h5>
                                    <p class="card-text text-muted">{{pr.descripcion}} ...</p>
                                    <p class="card-text">${{pr.precio}}</p>
                                    <a class="btn btn_abajo boton_ver_mas" href="{% url 'verProducto' pr.id %}">Ver mas</a> 
                                </div>
                            </div>  
                           </div>      
                        {%endfor%}
                </div>
            </div>

</div>
{%endblock%}

CARRITO/templates/productos/resultados_buqueda.html
{% extends "layout.html" %}

{% block title %} 
    Productos Encontrados
{%endblock%}


{% block content %} 

    <div class="contenedor_productos container">

    {% if mensaje %}

        <div>{{categoria}}</div>
        <div>{{mensaje}}</div>

    {% elif productos_encontrados %}
        <p>Esta buscando : {{query}}</p>
            <p>Productos encontrados: {{productos_encontrados|length}} productos</p>
                            <div class="row">
                                <div class="card-group">
                                        {% for pr in productos_encontrados %}
                                        <div class="col-lg-4 col-sm-6 col-md-6 col-xs-12 d-flex align-items-stretch"> 
                                            <div class="card">
                                                <a href="{% url 'verProducto' pr.id %}"><img src="{{ pr.imagenProducto.url }}" class="card-img-top" alt="Imagen producto" height="200px" width="auto" ></a>
                                                <div class="card-body">
                                                    <h5 class="card-title"><a class='link_pr_carro' href="{% url 'verProducto' pr.id %}">{{pr.titulo}}</a></h5>
                                                    <p class="card-text text-muted">{{pr.descripcion}} ...</p>
                                                    <p class="card-text text-muted">{{pr.categoria}}</p>
                                                    <p class="card-text">${{pr.precio}}</p>
                                                    <a class="btn btn_abajo boton_ver_mas" href="{% url 'verProducto' pr.id %}">Ver mas</a> 
                                                </div>
                                            </div>  
                                           </div>      
                                        {%endfor%}
                                </div>
                            </div>
    {%elif productos%}

                <div class="categoria_info">{{categoria}}</div>

                  
                <div class="row">
                    <div class="card-group">
                            {% for pr in productos%}
                            <div class="col-lg-4 col-sm-6 col-md-6 col-xs-12 d-flex align-items-stretch"> 
                                <div class="card">
                                    <a href="{% url 'verProducto' pr.id %}"><img src="{{ pr.imagenProducto.url }}" class="card-img-top" alt="Imagen producto" height="200px" width="auto" ></a>
                                    <div class="card-body">
                                        <h5 class="card-title"><a class='link_pr_carro' href="{% url 'verProducto' pr.id %}">{{pr.titulo}}</a></h5>
                                        <p class="card-text text-muted">{{pr.descripcion}} ...</p>
                                        <p class="card-text text-muted">{{pr.categoria}}</p>
                                        <p class="card-text">${{pr.precio}}</p>
                                        <a class="btn btn_abajo boton_ver_mas" href="{% url 'verProducto' pr.id %}">Ver mas</a> 
                                    </div>
                                </div>  
                               </div>      
                            {%endfor%}
                    </div>
                </div>


        {% else %}
                 <p>Articulos no encontrados ...</p>

        {%endif%}
    </div>

{%endblock%}

CARRITO/templates/productos/verProducto.html
{% extends "layout.html" %}

{% block title %} 
    Producto
{%endblock%}


{% block content %} 

        {% load static %}

        {% if mensaje %}
            <div class = "mensaje">{{mensaje}}</div>
        {% endif %}

        {% if producto %}

                <div class="row">

                    <div class="col-lg-6 col-sm-12 col-xs-12 col-ms-6 imagen_producto">

                            <img src="{{producto.imagenProducto.url}}" alt="Imagen producto: {{producto.titulo}}" width="70%">
                            

                    </div>

                    <div class="col info_producto">
                        <div class="row">
                            <div class="col-12">
                                <p><span class="etiqueta">Producto: </span><br>{{producto.titulo}}</p>
                                <p><span class="etiqueta">Descripcion: </span><br>{{producto.descripcion}}</p>
                                <p><span class="etiqueta">Precio: </span><br>${{producto.precio}}</p>
                            </div>
                            {% if not request.user.is_superuser %}
                                    <div class="col-12">
                                        <div class="btn-group">
                                            <a class="btn boton_ver_mas" href="">Comprar</a>
                                            <a class="btn boton_ver_mas" href="{% url 'AgregarCarrito' producto.id  %}">Agregar al carrito</a>
                                        </div>
                                    </div>
                            {% endif %}           
                            {% if request.user.is_superuser %}
                            <div class="col-12">
                                <div class="btn-group">
                                    <a class="btn boton_ver_mas" href="{% url 'EditarProducto' producto.id  %}">Editar Producto</a>
                                    <a class="btn boton_ver_mas" id="btn_eliminar" onclick="eliminarProducto()">Eliminar Producto</a> 
                                </div>
                            </div>
                            <div class="col-12" id="botonera" style="margin-top: 2em;" hidden>
                                <p style="margin-bottom: 2em;">¿Eliminar este producto?</p>
                                <div class="btn-group">
                                    <a class="btn boton_ver_mas" href="{% url 'EliminarProducto' producto.id %}">Aceptar</a>
                                    <a class="btn boton_ver_mas" id="cancelarEliminacion" onclick="ocultarBotoner()">Cancelar</a> 
                                </div>
                            </div>

                            {% endif %}
                        </div>
                        </div>
                    </div>

        {% else %}
                {{vacio}}
        {% endif %}  
{%endblock%}